spring:
  application:
    name: spring-cloud-api-gateway
server:
  port: 9000
main:
  web-application-type: reactive
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: localhost