//Define Fruit Object type with required properties like id, name, image, unit and price

// Note:As per test requirement, Fruits API should be running on port 3000
function getFruits() {
    //Return the promise returned by the fetch() method

    //Successful promise callback function should convert the response body text to json object and return the promise as result.
    
    
    //Returned successful promise callback should call `transform()` method by passing the json object as argument
}

//Inside transform() function, iterate the json data passed as parameter.
//Then transform each fruit to transformedFruit object that mirrors Fruit type 
function transform() {
    //call showFruit() function for each transformedFruit object
}

//Inside showFruit() function, pass transformedFruit object as parameter
function showFruit() {
    //display each transformedFruit as card by creating HTML code as string and appending it to the div container
}

//compiler error for "module" will be resolved once node_modules folder is generated by giving 'npm install' command in the terminal
// do not delete the code given below, it is written to export the functions to be tested
module.exports = {
    getFruits
}
